- name: Configuration des interfaces Cisco L3
  hosts: csr1000
  gather_facts: no
  tasks:
    - name: Configurer les interfaces L3
      cisco.ios.ios_l3_interfaces:
        config:
          - name: GigabitEthernet1
            ipv4:
              - address: 
                secondary: true
          - name: GigabitEthernet2
            ipv4:
              - address: 192.168.2.1/24
          - name: GigabitEthernet3
            ipv4:
              - address: 192.168.3.1/24
          - name: GigabitEthernet4
            ipv4:
              - address: 192.168.4.1/24
        state: merged


